# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

import entity_pb2 as entity__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bproxy.proto\x12\x10sa.rpc.cli.proxy\x1a\x0c\x65ntity.proto\",\n\x03Rsp\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\"`\n\x0fSubscriptionRsp\x12\"\n\x03rsp\x18\x01 \x01(\x0b\x32\x15.sa.rpc.cli.proxy.Rsp\x12)\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x1b.sa.rpc.entity.Subscription2\xa0\x04\n\x05Proxy\x12K\n\x0fGetSubscription\x12\x13.sa.rpc.entity.Void\x1a!.sa.rpc.cli.proxy.SubscriptionRsp\"\x00\x12\x41\n\x0f\x41\x64\x64Subscription\x12\x15.sa.rpc.entity.String\x1a\x15.sa.rpc.cli.proxy.Rsp\"\x00\x12\x41\n\x0f\x44\x65lSubscription\x12\x15.sa.rpc.entity.String\x1a\x15.sa.rpc.cli.proxy.Rsp\"\x00\x12I\n\x13NewTickRecordStream\x12\x13.sa.rpc.entity.Void\x1a\x19.sa.rpc.entity.TickRecord\"\x00\x30\x01\x12K\n\x14NewOrderRecordStream\x12\x13.sa.rpc.entity.Void\x1a\x1a.sa.rpc.entity.OrderRecord\"\x00\x30\x01\x12U\n\x19NewOrderQueueRecordStream\x12\x13.sa.rpc.entity.Void\x1a\x1f.sa.rpc.entity.OrderQueueRecord\"\x00\x30\x01\x12U\n\x19NewStockQuoteRecordStream\x12\x13.sa.rpc.entity.Void\x1a\x1f.sa.rpc.entity.StockQuoteRecord\"\x00\x30\x01\x42\x16Z\x14l2-push-go/rpc/proxyb\x06proto3')

_RSP = DESCRIPTOR.message_types_by_name['Rsp']
_SUBSCRIPTIONRSP = DESCRIPTOR.message_types_by_name['SubscriptionRsp']
Rsp = _reflection.GeneratedProtocolMessageType('Rsp', (_message.Message,), {
    'DESCRIPTOR': _RSP,
    '__module__': 'proxy_pb2'
    # @@protoc_insertion_point(class_scope:sa.rpc.cli.proxy.Rsp)
})
_sym_db.RegisterMessage(Rsp)

SubscriptionRsp = _reflection.GeneratedProtocolMessageType('SubscriptionRsp', (_message.Message,), {
    'DESCRIPTOR': _SUBSCRIPTIONRSP,
    '__module__': 'proxy_pb2'
    # @@protoc_insertion_point(class_scope:sa.rpc.cli.proxy.SubscriptionRsp)
})
_sym_db.RegisterMessage(SubscriptionRsp)

_PROXY = DESCRIPTOR.services_by_name['Proxy']
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b'Z\024l2-push-go/rpc/proxy'
    _RSP._serialized_start = 47
    _RSP._serialized_end = 91
    _SUBSCRIPTIONRSP._serialized_start = 93
    _SUBSCRIPTIONRSP._serialized_end = 189
    _PROXY._serialized_start = 192
    _PROXY._serialized_end = 736
# @@protoc_insertion_point(module_scope)
